# Generated by Django 6.0.7 on 2026-10-05 18:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('shots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('rec_timecode', models.IntegerField(blank=True, help_text='Start position of the shot in the edit, in frames.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='record timecode')),
                ('duration', models.IntegerField(blank=True, help_text='Length of the shot, in frames.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='duration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('groups', models.ManyToManyField(blank=True, related_name='shots', to='shots.shotgroup', verbose_name='groups')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='projects.project', verbose_name='project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'shot',
                'verbose_name_plural': 'shots',
                'ordering': ['project', 'name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_shot_name_per_project')],
            },
        ),
    ]
