# Hand-written rather than autogenerated: makemigrations prompts
# interactively for a one-off default when adding a required FK to an
# existing model, and there's no sane default here anyway - any `Shot`
# row created before this migration predates `ShotStatus` entirely, so
# it has no real status to backfill to. Pre-release, no production
# data to protect (same reasoning as the `shot_groups` -> `shots` app
# rename), so existing shots are simply cleared first.

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_existing_shots(apps, schema_editor):
    Shot = apps.get_model("shots", "Shot")
    Shot.objects.all().delete()


class Migration(migrations.Migration):

    # Postgres refuses an ALTER TABLE on a table that still has pending
    # trigger events from an earlier DELETE in the same transaction
    # (the M2M-through delete for `groups` counts) - splitting this
    # across transactions avoids it.
    atomic = False

    dependencies = [
        ("companies", "0001_initial"),
        ("shots", "0002_shot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShotStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("color", models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Color must be a 6-digit hex code, e.g. #FF5733.", regex="^#[0-9A-Fa-f]{6}$")], verbose_name="color")),
                ("order", models.IntegerField(blank=True, help_text="Sort position among the primary workflow statuses. Leave blank for an exception/side status (e.g. cancelled, on hold) that isn't part of the main sequence.", null=True, verbose_name="order")),
                ("is_default", models.BooleanField(default=False, verbose_name="default")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shot_statuses", to="companies.company", verbose_name="company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="created by")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="updated by")),
            ],
            options={
                "verbose_name": "shot status",
                "verbose_name_plural": "shot statuses",
                "ordering": ["company", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="shotstatus",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="unique_shot_status_name_per_company"),
        ),
        migrations.RunPython(delete_existing_shots, migrations.RunPython.noop),
        # No default needed - the RunPython step above guarantees the
        # table is empty by the time this runs, so there are no existing
        # rows to backfill a value for.
        migrations.AddField(
            model_name="shot",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="shots", to="shots.shotstatus", verbose_name="status"),
        ),
    ]
