/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticate with an email and password and receive a new pair of JWT tokens.
         *
         *     - The **access token** is short-lived and must be sent as `Authorization: Bearer <access_token>` on protected endpoints.
         *     - The **refresh token** is long-lived and can be exchanged for a new pair at `POST /api/v1/auth/refresh/`.
         */
        post: operations["postLogincontrollerApiV1AuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revoke the access token used to authenticate this request, so it can no longer be used, even if it has not expired yet.
         *
         *     Optionally pass the paired **refresh token** in the body to revoke it too and fully close the session; otherwise it stays valid until it expires naturally.
         */
        post: operations["postLogoutcontrollerApiV1AuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Exchange a valid, non-revoked refresh token for a brand new access/refresh token pair, without sending the user's password again.
         */
        post: operations["postRefreshcontrollerApiV1AuthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Return a paginated list of users, optionally filtered by `search` against email, first and last name.
         */
        get: operations["getUserlistcontrollerApiV1Users"];
        put?: never;
        /**
         * Create a user
         * @description Create a new user account, optionally with an avatar. Send as `multipart/form-data`: regular fields for `email`, `password`, `first_name`, `last_name`, plus an optional `avatar` file field. If `password` is omitted, the account is created with an unusable password.
         */
        post: operations["postUserlistcontrollerApiV1Users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Return the profile of the user identified by the provided access token.
         */
        get: operations["getMecontrollerApiV1UsersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Return a single user by id.
         */
        get: operations["getUserdetailcontrollerApiV1UsersUserId"];
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Permanently delete a user account.
         */
        delete: operations["deleteUserdetailcontrollerApiV1UsersUserId"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Partially update a user, optionally replacing or removing their avatar in the same request. Send as `multipart/form-data`: any of `first_name`, `last_name`, `is_active`, `remove_avatar`, plus an optional `avatar` file field. Only fields actually present are changed.
         */
        patch: operations["patchUserdetailcontrollerApiV1UsersUserId"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorDetail
         * @description Base schema for error details description.
         */
        ErrorDetail: {
            /** Msg */
            msg: string;
            /** Type */
            type?: string;
            /** Loc */
            loc?: (number | string)[];
        };
        /**
         * ErrorModel
         * @description Default error response schema.
         *
         *     Can be customized.
         *     See :ref:`customizing-error-messages` for more details.
         */
        ErrorModel: {
            /** Detail */
            detail: components["schemas"]["ErrorDetail"][];
        };
        /**
         * LoginPayload
         * @description Credentials used to obtain a new access/refresh token pair.
         */
        LoginPayload: {
            /**
             * Email
             * @description Registered user's email address.
             * @example user@example.com
             */
            email: string;
            /**
             * Password
             * @description User's password.
             * @example W5&faQ36$f6
             */
            password: string;
        };
        /**
         * LogoutPayload
         * @description Optional payload for logging out.
         *
         *     If a refresh token is provided, it is blocklisted together with the
         *     access token used to authenticate this request, so it can no longer
         *     be used to mint new token pairs either.
         */
        LogoutPayload: {
            /**
             * Refresh Token
             * @description Refresh token issued alongside the access token used for this request. If provided, it is revoked too, fully closing this session.
             */
            refresh_token?: string | null;
        };
        /**
         * MessageResponse
         * @description A simple textual confirmation message.
         */
        MessageResponse: {
            /**
             * Detail
             * @description Human-readable result message.
             */
            detail: string;
        };
        /**
         * RefreshPayload
         * @description A refresh token used to obtain a new token pair without re-authenticating.
         */
        RefreshPayload: {
            /**
             * Refresh Token
             * @description A valid, non-expired, non-revoked refresh token.
             */
            refresh_token: string;
        };
        /**
         * TokenPairResponse
         * @description A freshly issued pair of JWT tokens.
         */
        TokenPairResponse: {
            /**
             * Access Token
             * @description Short-lived JWT. Send it as `Authorization: Bearer <access_token>` on protected endpoints.
             */
            access_token: string;
            /**
             * Refresh Token
             * @description Long-lived JWT. Exchange it for a new token pair at `POST /api/v1/auth/refresh/`.
             */
            refresh_token: string;
        };
        /**
         * UserCreateIn
         * @description Payload for `POST /api/v1/users/`.
         */
        UserCreateIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description If omitted, the account is created with an unusable password (e.g. for an invite-based flow).
             */
            password?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * UserListOut
         * @description A page of users.
         */
        UserListOut: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /**
             * Total
             * @description Total number of users matching filters.
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * UserOut
         * @description Public representation of a user.
         */
        UserOut: {
            /**
             * Id
             * @description Internal numeric user identifier.
             */
            id: number;
            /**
             * Email
             * @description User's email address.
             */
            email: string;
            /**
             * First Name
             * @description User's first name.
             */
            first_name: string;
            /**
             * Last Name
             * @description User's last name.
             */
            last_name: string;
            /**
             * Avatar
             * @description Absolute URL of the user's avatar image, or null if none.
             */
            avatar?: string | null;
            /**
             * Is Active
             * @description Whether the user account is active.
             */
            is_active: boolean;
            /**
             * Date Joined
             * Format: date-time
             * @description When the user account was created.
             */
            date_joined: string;
        };
        /**
         * UserUpdateIn
         * @description Payload for `PATCH /api/v1/users/<id>/`. All fields are optional.
         */
        UserUpdateIn: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Remove Avatar
             * @description Set to true to delete the current avatar. Ignored if a new `avatar` file is also sent in the same request.
             * @default false
             */
            remove_avatar: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postLogincontrollerApiV1AuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credentials used to obtain a new access/refresh token pair. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description A new access/refresh token pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postLogoutcontrollerApiV1AuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Optional payload for logging out.
         *
         *     If a refresh token is provided, it is blocklisted together with the
         *     access token used to authenticate this request, so it can no longer
         *     be used to mint new token pairs either.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutPayload"];
            };
        };
        responses: {
            /** @description Confirmation that the session was closed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postRefreshcontrollerApiV1AuthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A refresh token used to obtain a new token pair without re-authenticating. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshPayload"];
            };
        };
        responses: {
            /** @description A new access/refresh token pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getUserlistcontrollerApiV1Users: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Number of users per page. */
                page_size?: number;
                /** @description Case-insensitive match against email, first or last name. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postUserlistcontrollerApiV1Users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Payload for `POST /api/v1/users/`. Files accepted alongside a user create/update payload.
         *
         *     `avatar` is optional: omit the field entirely to leave it untouched
         *     (on update) or create the user without one (on create).
         */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                } & components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description The created user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getMecontrollerApiV1UsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The currently authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        /**
         * @description Payload for `PATCH /api/v1/users/<id>/`. All fields are optional. Files accepted alongside a user create/update payload.
         *
         *     `avatar` is optional: omit the field entirely to leave it untouched
         *     (on update) or create the user without one (on create).
         */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                } & components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
