/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticate with an email and password. On success, the access and refresh tokens are set as `httponly` cookies - they are never exposed to the response body or to JavaScript - and the authenticated user is returned.
         *
         *     - The **access token** cookie is sent with every API request and is short-lived.
         *     - The **refresh token** cookie is only sent to `POST /api/v1/auth/refresh/` and is long-lived.
         */
        post: operations["postLogincontrollerApiV1AuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revoke the access token used to authenticate this request, so it can no longer be used even if it has not expired yet, and drop both token cookies. The refresh token is not revoked server-side - it is only dropped client-side - and stays valid until it expires naturally.
         */
        post: operations["postLogoutcontrollerApiV1AuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Exchange a valid, non-revoked refresh cookie for a brand new pair of cookies, without sending the user's password again. There is no request body: the browser sends the refresh cookie on its own.
         */
        post: operations["postRefreshcontrollerApiV1AuthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List companies
         * @description Return a paginated list of companies the current user is a member of, optionally filtered by `search` against the name.
         */
        get: operations["getCompanylistcontrollerApiV1Companies"];
        put?: never;
        /**
         * Create a company
         * @description Create a new company. The creator is automatically added as an `admin` member.
         */
        post: operations["postCompanylistcontrollerApiV1Companies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a company
         * @description Return a single company by id.
         */
        get: operations["getCompanydetailcontrollerApiV1CompaniesCompanyId"];
        put?: never;
        post?: never;
        /**
         * Delete a company
         * @description Permanently delete a company and all its memberships.
         */
        delete: operations["deleteCompanydetailcontrollerApiV1CompaniesCompanyId"];
        options?: never;
        head?: never;
        /**
         * Update a company
         * @description Partially update a company. Only fields present are changed.
         */
        patch: operations["patchCompanydetailcontrollerApiV1CompaniesCompanyId"];
        trace?: never;
    };
    "/api/v1/companies/{company_id}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List company members
         * @description Return every member of the company.
         */
        get: operations["getCompanymemberlistcontrollerApiV1CompaniesCompanyIdMembers"];
        put?: never;
        /**
         * Add a company member
         * @description Add an existing user to the company with the given role.
         */
        post: operations["postCompanymemberlistcontrollerApiV1CompaniesCompanyIdMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/members/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a company member
         * @description Remove a member from the company.
         */
        delete: operations["deleteCompanymemberdetailcontrollerApiV1CompaniesCompanyIdMembersUserId"];
        options?: never;
        head?: never;
        /**
         * Update a company member's role
         * @description Change the role of an existing company member.
         */
        patch: operations["patchCompanymemberdetailcontrollerApiV1CompaniesCompanyIdMembersUserId"];
        trace?: never;
    };
    "/api/v1/companies/{company_id}/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a company's projects
         * @description Return a paginated list of projects within the given company that the current user is a member of, optionally filtered by `search` against the name.
         */
        get: operations["getProjectlistcontrollerApiV1CompaniesCompanyIdProjects"];
        put?: never;
        /**
         * Create a project
         * @description Create a new project within the company. The creator is automatically added as an `admin` member.
         */
        post: operations["postProjectlistcontrollerApiV1CompaniesCompanyIdProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a project
         * @description Return a single project by id.
         */
        get: operations["getProjectdetailcontrollerApiV1ProjectsProjectId"];
        put?: never;
        post?: never;
        /**
         * Delete a project
         * @description Permanently delete a project and all its memberships.
         */
        delete: operations["deleteProjectdetailcontrollerApiV1ProjectsProjectId"];
        options?: never;
        head?: never;
        /**
         * Update a project
         * @description Partially update a project. Only fields present are changed. `code` cannot be changed - it's immutable once set.
         */
        patch: operations["patchProjectdetailcontrollerApiV1ProjectsProjectId"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List project members
         * @description Return every member of the project.
         */
        get: operations["getProjectmemberlistcontrollerApiV1ProjectsProjectIdMembers"];
        put?: never;
        /**
         * Add a project member
         * @description Add an existing company member to the project with the given role. The target user must already be a member of the project's company.
         */
        post: operations["postProjectmemberlistcontrollerApiV1ProjectsProjectIdMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/members/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a project member
         * @description Remove a member from the project.
         */
        delete: operations["deleteProjectmemberdetailcontrollerApiV1ProjectsProjectIdMembersUserId"];
        options?: never;
        head?: never;
        /**
         * Update a project member's role
         * @description Change the role of an existing project member.
         */
        patch: operations["patchProjectmemberdetailcontrollerApiV1ProjectsProjectIdMembersUserId"];
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Return a paginated list of users, optionally filtered by `search` against email, first and last name.
         */
        get: operations["getUserlistcontrollerApiV1Users"];
        put?: never;
        /**
         * Create a user
         * @description Create a new user account, optionally with an avatar. Send as `multipart/form-data`: regular fields for `email`, `password`, `first_name`, `last_name`, plus an optional `avatar` file field. If `password` is omitted, the account is created with an unusable password.
         */
        post: operations["postUserlistcontrollerApiV1Users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Return the profile of the user identified by the provided access token.
         */
        get: operations["getMecontrollerApiV1UsersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Return a single user by id.
         */
        get: operations["getUserdetailcontrollerApiV1UsersUserId"];
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Permanently delete a user account.
         */
        delete: operations["deleteUserdetailcontrollerApiV1UsersUserId"];
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Partially update a user, optionally replacing or removing their avatar in the same request. Send as `multipart/form-data`: any of `first_name`, `last_name`, `is_active`, `remove_avatar`, plus an optional `avatar` file field. Only fields actually present are changed.
         */
        patch: operations["patchUserdetailcontrollerApiV1UsersUserId"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompanyCreateIn
         * @description Payload for `POST /api/v1/companies/`.
         */
        CompanyCreateIn: {
            /** Name */
            name: string;
            /**
             * Slug
             * @description URL-friendly identifier. If omitted, it's auto-derived from `name`.
             */
            slug?: string | null;
        };
        /**
         * CompanyListOut
         * @description A page of companies the current user belongs to.
         */
        CompanyListOut: {
            /** Items */
            items: components["schemas"]["CompanyOut"][];
            /**
             * Total
             * @description Total number of companies matching filters.
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * CompanyMemberCreateIn
         * @description Payload for `POST /api/v1/companies/<id>/members/`.
         */
        CompanyMemberCreateIn: {
            /** User Id */
            user_id: number;
            role?: components["schemas"]["Role"];
        };
        /**
         * CompanyMemberListOut
         * @description The full list of a company's members (not paginated).
         */
        CompanyMemberListOut: {
            /** Items */
            items: components["schemas"]["CompanyMemberOut"][];
        };
        /**
         * CompanyMemberOut
         * @description Public representation of a company membership.
         */
        CompanyMemberOut: {
            /**
             * Id
             * @description Internal numeric membership identifier.
             */
            id: number;
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Avatar
             * @description Absolute URL of the member's avatar image, or null if none.
             */
            avatar?: string | null;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CompanyMemberUpdateIn
         * @description Payload for `PATCH /api/v1/companies/<id>/members/<user_id>/`.
         */
        CompanyMemberUpdateIn: {
            role: components["schemas"]["Role"];
        };
        /**
         * CompanyOut
         * @description Public representation of a company.
         */
        CompanyOut: {
            /**
             * Id
             * @description Internal numeric company identifier.
             */
            id: number;
            /**
             * Name
             * @description Company name.
             */
            name: string;
            /**
             * Slug
             * @description URL-friendly identifier for the company.
             */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompanyUpdateIn
         * @description Payload for `PATCH /api/v1/companies/<id>/`. All fields are optional.
         */
        CompanyUpdateIn: {
            /** Name */
            name?: string | null;
            /** Slug */
            slug?: string | null;
        };
        /**
         * ErrorDetail
         * @description Base schema for error details description.
         */
        ErrorDetail: {
            /** Msg */
            msg: string;
            /** Type */
            type?: string;
            /** Loc */
            loc?: (number | string)[];
        };
        /**
         * ErrorModel
         * @description Default error response schema.
         *
         *     Can be customized.
         *     See :ref:`customizing-error-messages` for more details.
         */
        ErrorModel: {
            /** Detail */
            detail: components["schemas"]["ErrorDetail"][];
        };
        /**
         * LoginPayload
         * @description Credentials used to obtain a new access/refresh token pair.
         */
        LoginPayload: {
            /**
             * Email
             * @description Registered user's email address.
             * @example user@example.com
             */
            email: string;
            /**
             * Password
             * @description User's password.
             * @example W5&faQ36$f6
             */
            password: string;
        };
        /**
         * ProjectCreateIn
         * @description Payload for `POST /api/v1/companies/<company_id>/projects/`.
         */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /**
             * Code
             * @description Short, URL-friendly project code (e.g. `PRJ`). Set once - cannot be changed later.
             */
            code: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Start Date */
            start_date?: string | null;
            /** Deadline */
            deadline?: string | null;
        };
        /**
         * ProjectListOut
         * @description A page of projects the current user is a member of, within a company.
         */
        ProjectListOut: {
            /** Items */
            items: components["schemas"]["ProjectOut"][];
            /**
             * Total
             * @description Total number of projects matching filters.
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ProjectMemberCreateIn
         * @description Payload for `POST /api/v1/projects/<id>/members/`.
         *
         *     `user_id` must belong to a user who is already a `CompanyMembership`
         *     member of the project's company.
         */
        ProjectMemberCreateIn: {
            /** User Id */
            user_id: number;
            role?: components["schemas"]["Role"];
        };
        /**
         * ProjectMemberListOut
         * @description The full list of a project's members (not paginated).
         */
        ProjectMemberListOut: {
            /** Items */
            items: components["schemas"]["ProjectMemberOut"][];
        };
        /**
         * ProjectMemberOut
         * @description Public representation of a project membership.
         */
        ProjectMemberOut: {
            /**
             * Id
             * @description Internal numeric membership identifier.
             */
            id: number;
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Avatar
             * @description Absolute URL of the member's avatar image, or null if none.
             */
            avatar?: string | null;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectMemberUpdateIn
         * @description Payload for `PATCH /api/v1/projects/<id>/members/<user_id>/`.
         */
        ProjectMemberUpdateIn: {
            role: components["schemas"]["Role"];
        };
        /**
         * ProjectOut
         * @description Public representation of a project.
         */
        ProjectOut: {
            /**
             * Id
             * @description Internal numeric project identifier.
             */
            id: number;
            /** Company Id */
            company_id: number;
            /**
             * Name
             * @description Project name.
             */
            name: string;
            /**
             * Code
             * @description Short, URL-friendly project code (e.g. `PRJ`). Immutable.
             */
            code: string;
            /** Description */
            description: string;
            /**
             * Cover
             * @description Absolute URL of the project's cover image, or null if none.
             */
            cover?: string | null;
            /** Start Date */
            start_date: string | null;
            /** Deadline */
            deadline: string | null;
            /** Is Active */
            is_active: boolean;
            /** @description The user who created the project, or null if that user has since been deleted. */
            created_by: components["schemas"]["UserOut"] | null;
            /** @description The user who last updated the project, or null if that user has since been deleted. */
            updated_by: components["schemas"]["UserOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectUpdateIn
         * @description Payload for `PATCH /api/v1/projects/<id>/`. All fields are optional.
         *
         *     `code` is intentionally absent - it's immutable once the project is
         *     created.
         */
        ProjectUpdateIn: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "admin" | "producer" | "coordinator" | "executor" | "freelancer" | "client";
        /**
         * UserCreateIn
         * @description Payload for `POST /api/v1/users/`.
         */
        UserCreateIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description If omitted, the account is created with an unusable password (e.g. for an invite-based flow).
             */
            password?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /**
         * UserListOut
         * @description A page of users.
         */
        UserListOut: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /**
             * Total
             * @description Total number of users matching filters.
             */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * UserOut
         * @description Public representation of a user.
         */
        UserOut: {
            /**
             * Id
             * @description Internal numeric user identifier.
             */
            id: number;
            /**
             * Email
             * @description User's email address.
             */
            email: string;
            /**
             * First Name
             * @description User's first name.
             */
            first_name: string;
            /**
             * Last Name
             * @description User's last name.
             */
            last_name: string;
            /**
             * Avatar
             * @description Absolute URL of the user's avatar image, or null if none.
             */
            avatar?: string | null;
            /**
             * Is Active
             * @description Whether the user account is active.
             */
            is_active: boolean;
            /**
             * Date Joined
             * Format: date-time
             * @description When the user account was created.
             */
            date_joined: string;
        };
        /**
         * UserUpdateIn
         * @description Payload for `PATCH /api/v1/users/<id>/`. All fields are optional.
         */
        UserUpdateIn: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /**
             * Remove Avatar
             * @description Set to true to delete the current avatar. Ignored if a new `avatar` file is also sent in the same request.
             * @default false
             */
            remove_avatar: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postLogincontrollerApiV1AuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credentials used to obtain a new access/refresh token pair. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description The now-authenticated user. */
            200: {
                headers: {
                    /** @description Credentials must not be stored in any cache. */
                    "Cache-Control": string;
                    /** @description Access token, sent with every API request. */
                    "Set-Cookie: access_token": string;
                    /** @description Refresh token, only sent to the refresh endpoint. */
                    "Set-Cookie: refresh_token": string;
                    /** @description CSRF protection. */
                    "Set-Cookie: csrftoken": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postLogoutcontrollerApiV1AuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    /** @description Credentials must not be stored in any cache. */
                    "Cache-Control": string;
                    /** @description Sent back empty and expired, so it is dropped. */
                    "Set-Cookie: access_token": string;
                    /** @description Sent back empty and expired, so it is dropped. */
                    "Set-Cookie: refresh_token": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postRefreshcontrollerApiV1AuthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user. */
            200: {
                headers: {
                    /** @description Credentials must not be stored in any cache. */
                    "Cache-Control": string;
                    /** @description Access token, sent with every API request. */
                    "Set-Cookie: access_token": string;
                    /** @description Refresh token, only sent to the refresh endpoint. */
                    "Set-Cookie: refresh_token": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getCompanylistcontrollerApiV1Companies: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Number of companies per page. */
                page_size?: number;
                /** @description Case-insensitive match against the company name. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of companies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postCompanylistcontrollerApiV1Companies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Payload for `POST /api/v1/companies/`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateIn"];
            };
        };
        responses: {
            /** @description The created company. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getCompanydetailcontrollerApiV1CompaniesCompanyId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company. */
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested company. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteCompanydetailcontrollerApiV1CompaniesCompanyId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company. */
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchCompanydetailcontrollerApiV1CompaniesCompanyId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company. */
                company_id: number;
            };
            cookie?: never;
        };
        /** @description Payload for `PATCH /api/v1/companies/<id>/`. All fields are optional. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdateIn"];
            };
        };
        responses: {
            /** @description The updated company. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getCompanymemberlistcontrollerApiV1CompaniesCompanyIdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company. */
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The company's members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMemberListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postCompanymemberlistcontrollerApiV1CompaniesCompanyIdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company. */
                company_id: number;
            };
            cookie?: never;
        };
        /** @description Payload for `POST /api/v1/companies/<id>/members/`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyMemberCreateIn"];
            };
        };
        responses: {
            /** @description The created membership. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMemberOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteCompanymemberdetailcontrollerApiV1CompaniesCompanyIdMembersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company member. */
                company_id: number;
                /** @description URL path parameters identifying a single company member. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchCompanymemberdetailcontrollerApiV1CompaniesCompanyIdMembersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single company member. */
                company_id: number;
                /** @description URL path parameters identifying a single company member. */
                user_id: number;
            };
            cookie?: never;
        };
        /** @description Payload for `PATCH /api/v1/companies/<id>/members/<user_id>/`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyMemberUpdateIn"];
            };
        };
        responses: {
            /** @description The updated membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMemberOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getProjectlistcontrollerApiV1CompaniesCompanyIdProjects: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Number of projects per page. */
                page_size?: number;
                /** @description Case-insensitive match against the project name. */
                search?: string | null;
            };
            header?: never;
            path: {
                /** @description URL path parameters identifying a company's projects collection. */
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postProjectlistcontrollerApiV1CompaniesCompanyIdProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a company's projects collection. */
                company_id: number;
            };
            cookie?: never;
        };
        /** @description Payload for `POST /api/v1/companies/<company_id>/projects/`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description The created project. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getProjectdetailcontrollerApiV1ProjectsProjectId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project. */
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteProjectdetailcontrollerApiV1ProjectsProjectId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project. */
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchProjectdetailcontrollerApiV1ProjectsProjectId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project. */
                project_id: number;
            };
            cookie?: never;
        };
        /**
         * @description Payload for `PATCH /api/v1/projects/<id>/`. All fields are optional.
         *
         *     `code` is intentionally absent - it's immutable once the project is
         *     created.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description The updated project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getProjectmemberlistcontrollerApiV1ProjectsProjectIdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project. */
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project's members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postProjectmemberlistcontrollerApiV1ProjectsProjectIdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project. */
                project_id: number;
            };
            cookie?: never;
        };
        /**
         * @description Payload for `POST /api/v1/projects/<id>/members/`.
         *
         *     `user_id` must belong to a user who is already a `CompanyMembership`
         *     member of the project's company.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberCreateIn"];
            };
        };
        responses: {
            /** @description The created membership. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteProjectmemberdetailcontrollerApiV1ProjectsProjectIdMembersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project member. */
                project_id: number;
                /** @description URL path parameters identifying a single project member. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchProjectmemberdetailcontrollerApiV1ProjectsProjectIdMembersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single project member. */
                project_id: number;
                /** @description URL path parameters identifying a single project member. */
                user_id: number;
            };
            cookie?: never;
        };
        /** @description Payload for `PATCH /api/v1/projects/<id>/members/<user_id>/`. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMemberUpdateIn"];
            };
        };
        responses: {
            /** @description The updated membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getUserlistcontrollerApiV1Users: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Number of users per page. */
                page_size?: number;
                /** @description Case-insensitive match against email, first or last name. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    postUserlistcontrollerApiV1Users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Payload for `POST /api/v1/users/`. Files accepted alongside a user create/update payload.
         *
         *     `avatar` is optional: omit the field entirely to leave it untouched
         *     (on update) or create the user without one (on create).
         */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                } & components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description The created user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getMecontrollerApiV1UsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The currently authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    patchUserdetailcontrollerApiV1UsersUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL path parameters identifying a single user. */
                user_id: number;
            };
            cookie?: never;
        };
        /**
         * @description Payload for `PATCH /api/v1/users/<id>/`. All fields are optional. Files accepted alongside a user create/update payload.
         *
         *     `avatar` is optional: omit the field entirely to leave it untouched
         *     (on update) or create the user without one (on create).
         */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    avatar?: string;
                } & components["schemas"]["UserUpdateIn"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Raised when request components cannot be parsed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when auth was not successful */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when CSRF check failed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Raised when provided `Accept` header cannot be satisfied */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Raised when returned response does not match the response schema */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
