/**
 * Friendly aliases over the generated OpenAPI schema (src/api/schema.ts).
 *
 * schema.ts is generated by openapi-typescript from the backend's live
 * OpenAPI document and should never be hand-edited. Regenerate it
 * whenever the backend schemas change:
 *
 *   npx openapi-typescript http://localhost:8000/api/v1/docs/openapi.json \
 *     -o src/api/schema.ts
 *
 * (wired up as `just generate-api-types` at the repo root)
 */
import type { components, operations } from '@/api/schema'

export type UserOut = components['schemas']['UserOut']
export type UserListOut = components['schemas']['UserListOut']
export type UserCreateIn = components['schemas']['UserCreateIn']
export type UserUpdateIn = components['schemas']['UserUpdateIn']

export type UserListQuery = NonNullable<
  operations['getUserlistcontrollerApiV1Users']['parameters']['query']
>

export type CompanyOut = components['schemas']['CompanyOut']
export type CompanyListOut = components['schemas']['CompanyListOut']
export type CompanyCreateIn = components['schemas']['CompanyCreateIn']
export type CompanyUpdateIn = components['schemas']['CompanyUpdateIn']

export type CompanyListQuery = NonNullable<
  operations['getCompanylistcontrollerApiV1Companies']['parameters']['query']
>

export type CompanyMemberOut = components['schemas']['CompanyMemberOut']
export type CompanyMemberListOut = components['schemas']['CompanyMemberListOut']
export type CompanyMemberCreateIn = components['schemas']['CompanyMemberCreateIn']
export type CompanyMemberUpdateIn = components['schemas']['CompanyMemberUpdateIn']

// `CompanyMembership.role` and `ProjectMembership.role` are the exact same
// Python enum on the backend (the latter aliases the former), so the OpenAPI
// document only ever generates one `Role` schema - shared here under a
// name that doesn't imply it belongs to either resource specifically.
export type MembershipRole = components['schemas']['Role']
export type CompanyMembershipRole = MembershipRole

export type ProjectOut = components['schemas']['ProjectOut']
export type ProjectListOut = components['schemas']['ProjectListOut']
export type ProjectCreateIn = components['schemas']['ProjectCreateIn']
export type ProjectUpdateIn = components['schemas']['ProjectUpdateIn']

export type ProjectListQuery = NonNullable<
  operations['getProjectlistcontrollerApiV1CompaniesCompanyIdProjects']['parameters']['query']
>

export type ProjectMemberOut = components['schemas']['ProjectMemberOut']
export type ProjectMemberListOut = components['schemas']['ProjectMemberListOut']
export type ProjectMemberCreateIn = components['schemas']['ProjectMemberCreateIn']
export type ProjectMemberUpdateIn = components['schemas']['ProjectMemberUpdateIn']
export type ProjectMembershipRole = MembershipRole
