# Generated by Django 6.0.7 on 2026-10-08 06:40

import apps.versions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('shots', '0003_shotstatus_shot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10, verbose_name='type')),
                ('source', models.FileField(upload_to=apps.versions.models.version_upload_to, verbose_name='source file')),
                ('converted', models.FileField(blank=True, upload_to=apps.versions.models.version_upload_to, verbose_name='converted file')),
                ('thumb', models.FileField(blank=True, upload_to=apps.versions.models.version_upload_to, verbose_name='thumbnail')),
                ('width', models.PositiveIntegerField(help_text='In pixels.', verbose_name='width')),
                ('height', models.PositiveIntegerField(help_text='In pixels.', verbose_name='height')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Length in frames. Empty for images.', null=True, verbose_name='duration')),
                ('fps', models.FloatField(blank=True, help_text='Frames per second. Empty for images.', null=True, verbose_name='frame rate')),
                ('codec', models.CharField(blank=True, help_text='Video codec name, e.g. h264. Empty for images.', max_length=32, verbose_name='codec')),
                ('file_size', models.PositiveBigIntegerField(help_text='Size of the source file, in bytes.', verbose_name='file size')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project', verbose_name='project')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='shots.shot', verbose_name='shot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_version_name_per_project')],
            },
        ),
    ]
