# Generated by Django 6.0.7 on 2026-10-08 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('shots', '0003_shotstatus_shot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estimated hours')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='actual hours')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shot_tasks', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tasks', to='shots.shot', verbose_name='shot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'shot task',
                'verbose_name_plural': 'shot tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(editable=False, max_length=16, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='project')),
                ('shots', models.ManyToManyField(blank=True, related_name='tasks', through='tasks.ShotTask', to='shots.shot', verbose_name='shots')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='shottask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_tasks', to='tasks.task', verbose_name='task'),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a 6-digit hex code, e.g. #FF5733.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color')),
                ('order', models.IntegerField(blank=True, help_text="Sort position among the primary workflow statuses. Leave blank for an exception/side status (e.g. cancelled, on hold) that isn't part of the main sequence.", null=True, verbose_name='order')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'task status',
                'verbose_name_plural': 'task statuses',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='shottask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shot_tasks', to='tasks.taskstatus', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('abbreviation', models.CharField(help_text='Prefix of task codes of this type, e.g. CLN.', max_length=5, validators=[django.core.validators.RegexValidator(message='Abbreviation must be 2-5 uppercase Latin letters or digits.', regex='^[A-Z0-9]{2,5}$')], verbose_name='abbreviation')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a 6-digit hex code, e.g. #FF5733.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'task type',
                'verbose_name_plural': 'task types',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.tasktype', verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_task_status_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='shottask',
            constraint=models.UniqueConstraint(fields=('task', 'shot'), name='unique_task_per_shot'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_task_type_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('company', 'abbreviation'), name='unique_task_type_abbreviation_per_company'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_task_code_per_project'),
        ),
    ]
