# Generated by Django 6.0.7 on 2026-10-09 16:23

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shots', '0003_shotstatus_shot_status'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('user', 'user'), ('system', 'system')], default='user', max_length=10, verbose_name='type')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('event', models.CharField(blank=True, choices=[('version_uploaded', 'version uploaded'), ('task_added', 'task added'), ('status_changed', 'status changed'), ('assignee_changed', 'assignee changed')], help_text='What happened. Only for system messages.', max_length=32, verbose_name='event')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Details of the event. Only for system messages.', verbose_name='payload')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='reply to')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='shots.shot', verbose_name='shot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('versions', models.ManyToManyField(blank=True, related_name='chat_messages', to='versions.version', verbose_name='versions')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(upload_to=apps.chat.models.chat_attachment_upload_to, verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='file name')),
                ('size', models.PositiveBigIntegerField(help_text='In bytes.', verbose_name='size')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='content type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to='shots.shot', verbose_name='shot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'chat attachment',
                'verbose_name_plural': 'chat attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('emoji', models.CharField(max_length=64, verbose_name='emoji')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.message', verbose_name='message')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reactions',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['shot', 'id'], name='chat_msg_shot_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event', ''), ('type', 'user')), models.Q(('type', 'system'), models.Q(('event', ''), _negated=True)), _connector='OR'), name='chat_message_event_only_for_system'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('message', 'created_by', 'emoji'), name='unique_reaction_per_user_and_emoji'),
        ),
    ]
